[[actions]]
name = "play"
platform = "windows"
path = "DADM/DADM.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "DADM/DADM"
args = ["--launched-through-itch"]
